sudo: false
language: php
php:
  - '5.6'
before_install:
  - gem update --system
  - composer self-update
  - nvm install stable
  - nvm use stable
  - npm install -g grunt-cli
  - npm --version
  - node --version
install:
  - npm install
script:
  - npm test
